# Generated by Django 5.1.4 on 2024-12-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.status'),
        ),
    ]
